#!/bin/python3

from datetime import datetime, timezone, timedelta
import os

def time_delta(t1, t2):
    dt_format = "%a %d %b %Y %H:%M:%S %z"
    time1 = datetime.strptime(t1, dt_format)
    time2 = datetime.strptime(t2, dt_format)
    diff_seconds = abs(int((time1 - time2).total_seconds()))
    return str(diff_seconds)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    t = int(input())
    for t_itr in range(t):
        t1 = input()
        t2 = input()
        delta = time_delta(t1, t2)
        fptr.write(delta + '\n')
    fptr.close()
